#!/bin/bash

clipboard-history() {
  for i in $(seq 0 40); do
    qdbus-qt6 org.kde.klipper /klipper org.kde.klipper.klipper.getClipboardHistoryItem $i | paste -sd ' ' | cut -c1-80
  done
}

selected=$(clipboard-history | /usr/bin/rofi -dmenu -format i -i -p "clipboard")
if [ $? == 0 ]; then
  qdbus-qt6 org.kde.klipper /klipper org.kde.klipper.klipper.getClipboardHistoryItem $selected |
    head -c -1 |
    xargs -0 -IREPLACE qdbus-qt6 org.kde.klipper /klipper org.kde.klipper.klipper.setClipboardContents REPLACE
fi
