
#include "quantum_keycodes.h"
#include QMK_KEYBOARD_H

enum custom_keycodes {
  CTL_EXLM = SAFE_RANGE,
};


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_3(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, LCTL_T(KC_A), LSFT_T(KC_S), LALT_T(KC_D), KC_F, KC_G, KC_H, KC_J, RALT_T(KC_K), RSFT_T(KC_L), LCTL_T(KC_QUOT), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RGUI, MO(1), KC_SPC, SC_SENT, LT(2,KC_ESC), KC_RALT),
    [1] = LAYOUT_split_3x5_3(KC_ESC, KC_LT, KC_GRV, KC_GT, KC_PPLS, KC_PIPE, KC_LCBR, KC_TILD, KC_RCBR, KC_BSPC, CTL_EXLM, KC_CIRC, KC_PEQL, KC_DLR, KC_ASTR, KC_HASH, KC_LPRN, KC_PMNS, KC_RPRN, KC_COLN, KC_QUES, KC_AMPR, KC_AT, KC_PERC, KC_NO, KC_SCLN, KC_LBRC, KC_UNDS, KC_RBRC, KC_BSLS, KC_LGUI, KC_TRNS, KC_SPC, RSFT(KC_ENT), MO(3), KC_RALT),
    [2] = LAYOUT_split_3x5_3(KC_ESC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BSPC, KC_1, LSFT_T(KC_2), KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, MO(4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_COMM, KC_DOT, KC_SLSH, MO(6), MO(3), KC_TAB, KC_ENT, KC_TRNS, KC_RALT),
    [3] = LAYOUT_split_3x5_3(KC_ESC, LALT(KC_LEFT), RALT(KC_RGHT), KC_MPLY, KC_NO, TO(5), KC_PGUP, RCS(KC_TAB), RCTL(KC_TAB), KC_DEL, KC_LCTL, LSFT_T(KC_HOME), KC_PGDN, KC_END, KC_NO, KC_LEFT, KC_DOWN, KC_UP, RSFT_T(KC_RGHT), KC_RCTL, KC_NO, RCS(KC_X), RCS(KC_C), RCS(KC_V), LCTL(KC_LEFT), KC_BRID, KC_BRIU, KC_VOLD, KC_VOLU, KC_MUTE, KC_LGUI, KC_TRNS, KC_SPC, SC_SENT, KC_TRNS, KC_RALT),
    [4] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P7, KC_P8, KC_P9, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P4, KC_P5, KC_P6, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P1, KC_P2, KC_P3, KC_NO, KC_NO, KC_TRNS, KC_SPC, KC_PENT, KC_P0, KC_PDOT),
    [5] = LAYOUT_split_3x5_3(KC_ESC, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO, KC_NO, KC_BSPC, KC_DEL, KC_1, KC_2, KC_3, KC_7, KC_NO, KC_LEFT, KC_UP, KC_RGHT, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DOWN, KC_NO, KC_NO, KC_NO, KC_NO, KC_SPC, KC_ENT, KC_NO, KC_NO),
    [6] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F11, KC_F12, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  static uint16_t ctl_exlm_timer;
  switch (keycode) {
    case CTL_EXLM:
      if (record->event.pressed) {
        ctl_exlm_timer = timer_read();
        register_code(KC_LCTL);
      } else {
        unregister_code(KC_LCTL);
        if (timer_elapsed(ctl_exlm_timer) < TAPPING_TERM) {
          SEND_STRING("!");
        }
      }
      return false;
  }
  return true;
}

#ifdef ENCODER_MAP_ENABLE
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] =
        {
            ENCODER_CCW_CW(KC_VOLD, KC_VOLU),
            ENCODER_CCW_CW(KC_MPRV, KC_MNXT),
            ENCODER_CCW_CW(RM_VALD, RM_VALU),
            ENCODER_CCW_CW(KC_RGHT, KC_LEFT),
        },
    [1] =
        {
            ENCODER_CCW_CW(KC_VOLD, KC_VOLU),
            ENCODER_CCW_CW(KC_MPRV, KC_MNXT),
            ENCODER_CCW_CW(RM_VALD, RM_VALU),
            ENCODER_CCW_CW(KC_RGHT, KC_LEFT),
        },
    [2] =
        {
            ENCODER_CCW_CW(KC_VOLD, KC_VOLU),
            ENCODER_CCW_CW(KC_MPRV, KC_MNXT),
            ENCODER_CCW_CW(RM_VALD, RM_VALU),
            ENCODER_CCW_CW(KC_RGHT, KC_LEFT),
        },
    [3] =
        {
            ENCODER_CCW_CW(KC_VOLD, KC_VOLU),
            ENCODER_CCW_CW(KC_MPRV, KC_MNXT),
            ENCODER_CCW_CW(RM_VALD, RM_VALU),
            ENCODER_CCW_CW(KC_RGHT, KC_LEFT),
        },
};
#endif
